---
title: "Conchina Officinalis SDM analysis"
author: "José Carlos"
date: "`r Sys.Date()`"
output:
  html_document:
    css: styles.css
    toc: yes
    toc_float: yes
    number_sections: yes
    theme: simplex
    highlight: tango
    df_print: kable
    code_folding: "hide"
    keep_md: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Packages
library(terra)
library(tidyterra)
library(sf)
library(tidyverse)
library(ggpubr)
```


```{r functions, echo=FALSE, message=FALSE, warning=FALSE}
read_current_projections <- function(cutoff_value, apply_cutoff = T, binarize = F, clip_layer) {
  # Validación de incompatibilidad
  if (apply_cutoff && binarize) {
    stop("Los argumentos 'apply_cutoff' y 'binarize' no pueden ser ambos TRUE. Elige solo uno.")
  }

  sdm <- rast(
    "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_Current_EM/proj_Current_EM_cinchona_ensemble.tif"
  ) / 1000

  if (!is.null(clip_layer)) {
    sdm <- crop(sdm, clip_layer, mask = TRUE)
  }

  if (apply_cutoff) {
    # Apply the cutoff value
    sdm[sdm < cutoff_value] <- 0
  }
  if (binarize) {
    # Binarize the projection
    sdm[sdm >= cutoff_value] <- 1
    sdm[sdm < cutoff_value] <- 0

    cls <- data.frame(id = 0:1, cover = c("No", "Yes"))
    levels(sdm) <- cls
  }

  names(sdm) <- "Current"
  return(sdm)
}

read_future_projections <- function(cutoff_value, apply_cutoff = TRUE, binarize = FALSE, clip_layer, desired_scenario = NULL, desired_time = NULL) {
  if (apply_cutoff && binarize) {
    stop("Los argumentos 'apply_cutoff' y 'binarize' no pueden ser ambos TRUE. Elige solo uno.")
  }

  sdm_paths <- list(
    "SSP3-7.0 2011-2040" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp370_2011-2040_EM/proj_ssp370_2011-2040_EM_cinchona_ensemble.tif",
    "SSP3-7.0 2041-2070" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp370_2041-2070_EM/proj_ssp370_2041-2070_EM_cinchona_ensemble.tif",
    "SSP3-7.0 2071-2100" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp370_2071-2100_EM/proj_ssp370_2071-2100_EM_cinchona_ensemble.tif",
    "SSP5-8.5 2011-2040" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp585_2011-2040_EM/proj_ssp585_2011-2040_EM_cinchona_ensemble.tif",
    "SSP5-8.5 2041-2070" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp585_2041-2070_EM/proj_ssp585_2041-2070_EM_cinchona_ensemble.tif",
    "SSP5-8.5 2071-2100" = "C:/SCIENCE/2025_INIA_Cinchona/SDM_output/cinchona/proj_ssp585_2071-2100_EM/proj_ssp585_2071-2100_EM_cinchona_ensemble.tif"
  )
  
  if(!is.null(desired_scenario)) {
    sdm_paths <- sdm_paths[grep(paste0("^", desired_scenario), names(sdm_paths))]
  }
  if(!is.null(desired_time)) {
    sdm_paths <- sdm_paths[grep(desired_time, names(sdm_paths))]
  }
  

  sdm_list <- lapply(names(sdm_paths), function(n) {
    r <- rast(sdm_paths[[n]]) / 1000
    names(r) <- n
    r
  })

  sdm <- do.call(c, sdm_list)

  if (!is.null(clip_layer)) {
    sdm <- crop(sdm, clip_layer, mask = TRUE)
  }

  previous_names <- names(sdm)

  if (apply_cutoff) {
    sdm <- app(sdm, fun = function(x) ifelse(x < cutoff_value, 0, x))
  }

  if (binarize) {
    sdm <- app(sdm, fun = function(x) ifelse(x >= cutoff_value, 1, 0))
    
    # Aplicar niveles a todas las capas (opcional)
    for (i in 1:nlyr(sdm)) {
      levels(sdm[[i]]) <- data.frame(id = 0:1, cover = c("No", "Yes"))
    }
  }

  names(sdm) <- previous_names
  return(sdm)
}

```



# SDM projections

```{r figure_x1, echo=FALSE, message=FALSE, warning=FALSE, out.width = "100%"}

aoi_peru <- rnaturalearth::ne_states("Peru", returnclass = "sf") %>% 
  summarise()

# Leer el umbral de corte
threshold <- read.csv("C:/SCIENCE/2025_INIA_Cinchona/SDM_output/single_eval.csv") %>%
  summarise(
    cutoff = median(cutoff, na.rm = TRUE) / 1000,
    validation = median(validation, na.rm = TRUE)
  )

# Leer proyecciones actual y futura
sdm_current <- read_current_projections(
  cutoff_value = threshold$cutoff,
  apply_cutoff = T,
  binarize = F,
  clip_layer = aoi_peru
)

names(sdm_current) <- "Current"

sdm_future <- read_future_projections(
  cutoff_value = threshold$cutoff,
  apply_cutoff = T,
  binarize = F,
  clip_layer = aoi_peru
)


plot_map_current <- function(r) {
  ggplot() +
    geom_spatraster(data = r) +
    scale_fill_whitebox_c(
      palette = "muted", direction = 1,
      breaks = seq(0, 1, 0.25), limits = c(0, 1),
      na.value = "transparent"
    ) +
    labs(
      fill = "Habitat suitability",
      title = names(r)
    ) +
    scale_x_continuous(n.breaks = 3) +
    guides(fill = guide_colourbar(order = 1, title.position = "top", title.hjust = 0.5)) +
    theme_bw(base_size = 8)+
    theme(
      legend.position = "bottom",
      plot.title = element_text(hjust = 0.5, size = 12)
    )
}
plot_map_future <- function(r) {
  ggplot() +
    geom_spatraster(data = r) +
    scale_fill_whitebox_c(
      palette = "muted", direction = 1,
      breaks = seq(0, 1, 0.25), limits = c(0, 1),
      na.value = "transparent"
    ) +
    labs(
      fill = "Habitat suitability"
    ) +
    guides(fill = guide_colourbar(order = 1, title.position = "top", title.hjust = 0.5)) +
    theme_void(base_size = 8)+
    theme(
      legend.position = "bottom",
      plot.title = element_text(hjust = 0.5, size = 12)
    )+
    facet_wrap(~lyr, ncol = 3)
}

p1 <- plot_map_current(sdm_current) 

p2 <- plot_map_future(sdm_future)



fig <- ggarrange(
  p1, p2,
  ncol = 2, nrow = 1,
  align = "hv",
  labels = c("a)", "b)"),
  widths = c(0.5, 0.75),
  common.legend = T, legend = "bottom"
)


ggsave("C:/SCIENCE/2025_INIA_Cinchona/Manuscript/images/Figure_X1.png", fig,
  units = "mm",
  dpi = 300, width = 183, height = 120
)

```

# Cambio de hábitat
```{r habitat_change, echo=FALSE, message=FALSE, warning=FALSE, out.width = "100%"}
myBiomodRangeSize <- biomod2::bm_RangeSize(
  proj.current = sdm_current,
  proj.future = sdm_future
)

changes <- myBiomodRangeSize$Diff.By.Pixel
changes[changes == 0] <- NA


plot_map_change <- function(r) {
  ggplot() +
    geom_spatraster(data = r) +
    scale_fill_whitebox_c(
      palette = "muted", direction = -1,
      breaks = seq(-1, 1, 0.25), limits = c(-1, 1),
      na.value = "transparent"
    ) +
    geom_spatvector(data = aoi_peru, fill = "transparent", color = "gray90") +
    labs(
      fill = "Change in habitat suitability"
    ) +
    guides(fill = guide_colourbar(order = 1, title.position = "top", title.hjust = 0.5)) +
    theme_void(base_size = 8)+
    theme(
      legend.position = "bottom",
      plot.title = element_text(hjust = 0.5, size = 12)
    )+
    facet_wrap(~lyr, ncol = 3)+
    guides(
      fill = guide_colourbar(order = 1, title.position = "top", title.hjust = 0.5, keywidth = unit(5, "cm")))
}


p1 <- plot_map_current(sdm_current) 
p2 <- plot_map_change(changes)

fig <- ggarrange(
  p1, p2,
  ncol = 2, nrow = 1,
  align = "hv",
  labels = c("a)", "b)"),
  widths = c(0.5, 0.75),
  common.legend = F, legend = "bottom"
)


ggsave("C:/SCIENCE/2025_INIA_Cinchona/Manuscript/images/Figure_X2_changes.png", fig,
  units = "mm",
  dpi = 300, width = 183, height = 120
)


```


# Importancia de las variables

```{r variable_importance, echo=FALSE, message=FALSE, warning=FALSE, out.width = "100%"}
# Leerlos datos
varimp <- read.csv("C:/SCIENCE/2025_INIA_Cinchona/SDM_output/ensemble_varimp.csv")

# Calcular resumen por variable
varimp_summary <- varimp %>%
  group_by(expl.var) %>%
  summarise(
    median_imp = median(var.imp, na.rm = TRUE)
  )

# Graficar importancia de las variables
var_importance_plot <- varimp_summary %>%
  mutate(expl.var = case_when(
    expl.var == "bio1" ~ "Mean annual temperature (Bio1)",
    expl.var == "bio12" ~ "Annual precipitation (Bio12)",
    expl.var == "bio15" ~ "Precipitation seasonality (Bio15)",
    expl.var == "phh2o" ~ "pH",
    expl.var == "soc" ~ "Soil organic carbon (SOC)",
    expl.var == "bdod" ~ "Bulk density (BDOD)"
  )) %>% 
  arrange(median_imp) %>%
  mutate(expl.var = factor(expl.var, levels = expl.var)) %>%
  # mutate(expl.var = tidytext::reorder_within(expl.var, median_imp)) %>%
  ggplot(aes(x = median_imp, y = expl.var)) +
  geom_segment(aes(xend = 0, yend = expl.var)) +
  geom_point(size = 2, color = "#f18f01") +
  tidytext::scale_y_reordered() +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.01)) +
  labs(x = "Median variable importance\n(10 random permutations)")+
  theme_bw(base_size = 10) +
  theme(
    legend.position = "bottom",
    axis.title.y = element_blank()
  )

var_importance_plot

```

# Curvas de respuesta

Las curvas de respuesta obtenidas permiten visualizar la sensibilidad del modelo frente a la variable analizada. Es importante señalar que este enfoque asume la independencia entre variables, por lo que no captura posibles efectos de interacción.

```{r response_curves, echo=FALSE, message=FALSE, warning=FALSE, out.width = "100%"}
# Read single eval and select only those with validation boyce > 0.7
single_eval <- read.csv("C:/SCIENCE/2025_INIA_Cinchona/SDM_output/single_eval.csv") %>% 
  filter(validation > 0.7) 

# read response curves data and filter by the selected models 
response_curves_data <- read.csv("C:/SCIENCE/2025_INIA_Cinchona/SDM_output/response_curves.csv") %>% 
  filter(pred.name %in% single_eval$full.name) %>% 
  dplyr::select(-id)

response_curves_summary <- response_curves_data %>%
  group_by(expl.name, expl.val) %>%
  summarise(
    sd = sd(pred.val, na.rm = TRUE),
    se = sd / sqrt(n()),
    pred.val = median(pred.val, na.rm = TRUE),
  ) %>%
  mutate(
    expl.name = case_when(
      expl.name == "bio1" ~ "Mean annual temperature (Bio1)",
      expl.name == "bio12" ~ "Annual precipitation (Bio12)",
      expl.name == "bio15" ~ "Precipitation seasonality (Bio15)",
      expl.name == "phh2o" ~ "pH",
      expl.name == "soc" ~ "Soil organic carbon (SOC)",
      expl.name == "bdod" ~ "Bulk density (BDOD)"
    ),
    expl.name = factor(expl.name, 
                       levels = c("Mean annual temperature (Bio1)", 
                                  "Annual precipitation (Bio12)", 
                                  "Precipitation seasonality (Bio15)", 
                                  "pH", 
                                  "Soil organic carbon (SOC)", 
                                  "Bulk density (BDOD)"))
  ) %>% 
  mutate(expl.val = case_when(
    expl.name == "pH" ~ expl.val * 10,
    expl.name == "Soil organic carbon (SOC)" ~ expl.val * 10,
    expl.name == "Bulk density (BDOD)" ~ expl.val * 100,
    .default = expl.val
  ))

response_curves_plot <- ggplot(response_curves_summary, aes(x = expl.val, y = pred.val)) +
  geom_line(size = 1, color = "#e63946") +
  geom_ribbon(aes(ymin = pred.val - se, ymax = pred.val + se), alpha = 0.2, fill = "#e63946") +
  facet_wrap(~ expl.name, scales = "free_x") +
  labs(y = "Predicted suitability") +
  theme_bw(base_size = 10) +
  theme(
    legend.position = "bottom",
    axis.title.x = element_blank()
  )

response_curves_plot

#############

# # read response curves data
# response_curves_data <- read.csv("C:/SCIENCE/2025_INIA_Cinchona/SDM_output/response_curves.csv") %>% 
#   mutate(
#     expl.name = case_when(
#       expl.name == "bio1" ~ "Mean annual temperature (Bio1)",
#       expl.name == "bio12" ~ "Annual precipitation (Bio12)",
#       expl.name == "bio15" ~ "Precipitation seasonality (Bio15)",
#       expl.name == "phh2o" ~ "pH",
#       expl.name == "soc" ~ "Soil organic carbon (SOC)",
#       expl.name == "bdod" ~ "Bulk density (BDOD)"
#     ),
#     expl.name = factor(expl.name, 
#                        levels = c("Mean annual temperature (Bio1)", 
#                                   "Annual precipitation (Bio12)", 
#                                   "Precipitation seasonality (Bio15)", 
#                                   "pH", 
#                                   "Soil organic carbon (SOC)", 
#                                   "Bulk density (BDOD)"))
#   ) %>% 
#   mutate(expl.val = case_when(
#     expl.name == "pH" ~ expl.val * 10,
#     expl.name == "Soil organic carbon (SOC)" ~ expl.val * 10,
#     expl.name == "Bulk density (BDOD)" ~ expl.val * 100,
#     .default = expl.val
#   ))
#   
# response_curves_plot <- ggplot(response_curves_data, aes(x = expl.val, y = pred.val)) +
#   geom_line(size = 1, color = "red") +
#   facet_wrap(~ expl.name, scales = "free_x") +
#   labs(y = "Predicted suitability") +
#   theme_bw(base_size = 10) +
#   theme(
#     legend.position = "bottom",
#     axis.title.x = element_blank()
#   )
# 
# response_curves_plot

```




```